name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.npm
            target
            schemas/gschemas.compiled
            .eslintcache
            *.tsbuildinfo
          key: ${{ runner.os }}-shatter-${{ hashFiles('metadata.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-shatter-${{ hashFiles('metadata.json') }}-

      - name: Get dependencies
        run: npm ci

      - name: Build
        run: make zip-file --assume-old=node_modules/.package-lock.json

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: shatter-shell@adilhanney.com_*.zip
          if-no-files-found: error
          archive: false

      - name: Run lints
        run: npx eslint --cache --cache-strategy content
